USE [master]
GO
/****** Object:  Database [Project_PRN221]    Script Date: 9/18/2022 4:48:03 PM ******/
CREATE DATABASE [Project_PRN221]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Project_PRN221', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Project_PRN221.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Project_PRN221_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Project_PRN221_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [Project_PRN221] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Project_PRN221].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Project_PRN221] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Project_PRN221] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Project_PRN221] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Project_PRN221] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Project_PRN221] SET ARITHABORT OFF 
GO
ALTER DATABASE [Project_PRN221] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Project_PRN221] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Project_PRN221] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Project_PRN221] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Project_PRN221] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Project_PRN221] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Project_PRN221] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Project_PRN221] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Project_PRN221] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Project_PRN221] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Project_PRN221] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Project_PRN221] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Project_PRN221] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Project_PRN221] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Project_PRN221] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Project_PRN221] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Project_PRN221] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Project_PRN221] SET RECOVERY FULL 
GO
ALTER DATABASE [Project_PRN221] SET  MULTI_USER 
GO
ALTER DATABASE [Project_PRN221] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Project_PRN221] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Project_PRN221] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Project_PRN221] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Project_PRN221] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Project_PRN221] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'Project_PRN221', N'ON'
GO
ALTER DATABASE [Project_PRN221] SET QUERY_STORE = OFF
GO
USE [Project_PRN221]
GO
/****** Object:  Table [dbo].[CategorySong]    Script Date: 9/18/2022 4:48:04 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CategorySong](
	[IdCategory] [int] NOT NULL,
	[NameCategory] [nvarchar](max) NULL,
 CONSTRAINT [PK_CategorySong] PRIMARY KEY CLUSTERED 
(
	[IdCategory] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[History]    Script Date: 9/18/2022 4:48:04 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[History](
	[IdHistory] [int] NOT NULL,
	[IdUser] [int] NULL,
	[IdSong] [int] NULL,
 CONSTRAINT [PK_History] PRIMARY KEY CLUSTERED 
(
	[IdHistory] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ListDetail]    Script Date: 9/18/2022 4:48:04 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ListDetail](
	[IdListDetail] [int] NOT NULL,
	[IdSong] [int] NOT NULL,
	[IdList] [int] NOT NULL,
 CONSTRAINT [PK_ListDetail] PRIMARY KEY CLUSTERED 
(
	[IdListDetail] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PlayList]    Script Date: 9/18/2022 4:48:04 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PlayList](
	[IdList] [int] NOT NULL,
	[NameList] [nvarchar](max) NULL,
	[IdUser] [int] NULL,
 CONSTRAINT [PK_PlayList] PRIMARY KEY CLUSTERED 
(
	[IdList] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Singer]    Script Date: 9/18/2022 4:48:04 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Singer](
	[IDSinger] [int] NOT NULL,
	[NameSinger] [nvarchar](max) NULL,
	[YearOfBirth] [date] NULL,
	[Gender] [nvarchar](max) NULL,
	[Nationality] [nvarchar](max) NULL,
	[Biography] [nvarchar](max) NULL,
 CONSTRAINT [PK_Singer] PRIMARY KEY CLUSTERED 
(
	[IDSinger] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Song]    Script Date: 9/18/2022 4:48:04 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Song](
	[IdSong] [int] NOT NULL,
	[NameSong] [nvarchar](max) NULL,
	[UploadBy] [nvarchar](max) NULL,
	[Lyric] [nvarchar](max) NULL,
	[listens] [int] NOT NULL,
	[DateUpload] [date] NULL,
	[Sound] [nvarchar](max) NULL,
	[IdCategory] [int] NOT NULL,
	[IdSinger] [int] NOT NULL,
 CONSTRAINT [PK_Song] PRIMARY KEY CLUSTERED 
(
	[IdSong] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[User]    Script Date: 9/18/2022 4:48:04 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[User](
	[UserID] [int] NOT NULL,
	[UserName] [nvarchar](max) NULL,
	[Name] [nvarchar](max) NULL,
	[Pass] [nvarchar](max) NULL,
	[Email] [nvarchar](max) NULL,
	[Avatar] [image] NULL,
	[IsAdmin] [int] NOT NULL,
 CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED 
(
	[UserID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[History]  WITH CHECK ADD  CONSTRAINT [FK_History_Song] FOREIGN KEY([IdSong])
REFERENCES [dbo].[Song] ([IdSong])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[History] CHECK CONSTRAINT [FK_History_Song]
GO
ALTER TABLE [dbo].[History]  WITH CHECK ADD  CONSTRAINT [FK_History_User] FOREIGN KEY([IdHistory])
REFERENCES [dbo].[User] ([UserID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[History] CHECK CONSTRAINT [FK_History_User]
GO
ALTER TABLE [dbo].[ListDetail]  WITH CHECK ADD  CONSTRAINT [FK_ListDetail_PlayList] FOREIGN KEY([IdList])
REFERENCES [dbo].[PlayList] ([IdList])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[ListDetail] CHECK CONSTRAINT [FK_ListDetail_PlayList]
GO
ALTER TABLE [dbo].[ListDetail]  WITH CHECK ADD  CONSTRAINT [FK_ListDetail_Song] FOREIGN KEY([IdSong])
REFERENCES [dbo].[Song] ([IdSong])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[ListDetail] CHECK CONSTRAINT [FK_ListDetail_Song]
GO
ALTER TABLE [dbo].[PlayList]  WITH CHECK ADD  CONSTRAINT [FK_PlayList_User] FOREIGN KEY([IdUser])
REFERENCES [dbo].[User] ([UserID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[PlayList] CHECK CONSTRAINT [FK_PlayList_User]
GO
ALTER TABLE [dbo].[Song]  WITH CHECK ADD  CONSTRAINT [FK_Song_CategorySong] FOREIGN KEY([IdCategory])
REFERENCES [dbo].[CategorySong] ([IdCategory])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Song] CHECK CONSTRAINT [FK_Song_CategorySong]
GO
ALTER TABLE [dbo].[Song]  WITH CHECK ADD  CONSTRAINT [FK_Song_Singer] FOREIGN KEY([IdSinger])
REFERENCES [dbo].[Singer] ([IDSinger])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Song] CHECK CONSTRAINT [FK_Song_Singer]
GO
USE [master]
GO
ALTER DATABASE [Project_PRN221] SET  READ_WRITE 
GO
